#!/bin/sh
#
# 03-persist-multipath-wwids - Copyright (C) 2015 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

MULTIPATH_DIR="/etc/multipath"
WWIDS_PATH="${MULTIPATH_DIR}/wwids"

if [ ! -f "/config${WWIDS_PATH}" ]; then
    if [ ! -d "${MULTIPATH_DIR}" ]; then
        mkdir ${MULTIPATH_DIR}
    fi
    touch ${WWIDS_PATH}
    persist ${WWIDS_PATH}
fi
